name: Bump and Tag Version

on:
  push:
    branches:
      - master

jobs:
  bump:
    if: "!contains(github.event.head_commit.author.name, 'GITHUBACTION')"
    runs-on: ubuntu-latest
   
    steps:
      # Checkout action is required
      - uses: actions/checkout@v2
        with:
          token: $${{ secrets.ADMIN_TOKEN }}
      - name: Set up git for commits
        run: git config user.name "GITHUBACTION"
        timeout-minutes: 1
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Bump Versions
        uses: michmich112/version-bumper@master
        with:
          options-file: './bump-info.json'
          github-token: ${{ secrets.ADMIN_TOKEN }}
